### ISSUE TITLE
support private docker registry

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/seagull#4]
will be nice to support private docker registry like https://github.com/atc-/docker-registry-web/ 

It could be based on Docker Registry API.

thx

**Comment by geekpete** [comment]
Any progress on this? How's that better plan coming along?

**Comment by tobegit3hub** [comment]
Thanks @geekpete  for your concern. It's closed because we think not all seagull users need to manage their registry with the same tool.

We have found some tools which are nice for managing the registry like [harbor](https://github.com/vmware/harbor) and [pirate](https://github.com/tobegit3hub/pirate).
