### ISSUE TITLE
The container page has no value for attributes

### ISSUE THREAD

**Issue by llqzwh** [tobegit3hub/seagull#58]
Select one running container and check its resources, but there is no value for attributes. Does it need more configurations? Thanks!
![image](https://cloud.githubusercontent.com/assets/12825720/11991966/2c7ffc7e-aa5b-11e5-9df9-cc9db96704c8.png)

**Comment by tobegit3hub** [comment]
We don't need any configuration. Please run `docker version` to show the version of your docker daemon. @llqzwh

**Comment by llqzwh** [comment]
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64

**Comment by myml** [comment]
docker run -d -p 10086:10086 -v /var/run/docker.sock:/var/run/docker.sock tobegit3hub/seagull

**Comment by tobegit3hub** [comment]
It seems the change of docker remote API and I will have a look soon.

Thanks for reporting.

**Comment by rjorgenson** [comment]
I am having this same issue on Docker version 1.11.2, build b9f10c9 Ubuntu 16.04.1 docker.io package.

**Comment by tobegit3hub** [comment]
I can re-produce this issue now. It seems the docker remote APIs change and I could not get the containr's stats from this method in the newer version.

```
/* Wrap docker remote API to get container stats */
func (this *DockerapiController) GetContainerStats() {
	id := this.GetString(":id")
	address := "/containers/" + id + "/stats"
	result := RequestUnixSocket(address, "GET")
	this.Ctx.WriteString(result)
}
```

**Comment by tobegit3hub** [comment]
`Seagull` doesn't want `stream` APIs and need to call docker remote API when user requests. Because the `stats` API changes after v1.19 which refers to the comments about. I change the API call with the `stream` parameter and it works well for me.

![screen shot 2016-08-28 at 00 33 43](https://cloud.githubusercontent.com/assets/2715000/18028712/285b1cee-6cb8-11e6-847d-478635c486f8.png)

@llqzwh @myml @rjorgenson You can `docker pull tobegit3hub/seagull` to update the `Seagull` image and this should be fixed. Thanks for reporting ❤️
